name: CI/CD

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
      - name: Give gradle executable permission
        run : chmod +x ./gradlew
      - name: Run gradle build
        run: ./gradlew build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app-jar
          path: build/libs/*-all.jar




